app:
  name: "SpeakPeak"
  mode: "dev"
  port: "8080"
  start_time: "2024-03-12"
  machine_id: "1"

log:
  level: "info"
  path: "logs"
  filename: "app.log"
  max_size: 100
  max_backup: 3
  max_age: 28
  compress: true

mysql:
  host: "43.139.140.244"
  port: 3306
  user: "root"
  password: "fk$uXvBR3tBhvn%gTDxn"
  dbname: "speakpeak"

redis:
  host: "43.139.140.244"
  port: 6379
  password: ""
  db: 0
  pool_size: 10
