app:
  name: "SpeakPeak"
  mode: "dev"
  port: 3000

log:
  level: "info"
  path: "logs"
  filename: "app.log"
  max_size: 100
  max_backup: 3
  max_age: 28
  compress: true

mysql:
  host: "43.139.140.244"
  port: 3306
  user: "root"
  password: "root"
  dbname: "speakpeak"
